/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        canvas: 'rgb(var(--ion-background-color-rgb) / <alpha-value>)',
        panel: 'rgb(var(--app-surface-panel-rgb) / <alpha-value>)',
        elevated: 'rgb(var(--app-surface-elevated-rgb) / <alpha-value>)',
        surface: {
          muted: 'rgb(var(--app-surface-muted-rgb) / <alpha-value>)',
          glass: 'rgb(var(--app-surface-glass-rgb) / <alpha-value>)',
        },
        line: 'rgb(var(--app-border-color-rgb) / <alpha-value>)',
        text: {
          DEFAULT: 'rgb(var(--ion-text-color-rgb) / <alpha-value>)',
          muted: 'rgb(var(--ion-color-medium-rgb) / <alpha-value>)',
          subtle: 'rgb(var(--ion-color-medium-rgb) / <alpha-value>)',
          inverse: 'rgb(var(--app-inverse-text-color-rgb) / <alpha-value>)',
        },
        accent: {
          DEFAULT: 'rgb(var(--ion-color-primary-rgb) / <alpha-value>)',
          strong: 'rgb(var(--app-color-primary-strong-rgb) / <alpha-value>)',
          soft: 'rgb(var(--app-color-primary-soft-rgb) / <alpha-value>)',
        },
        success: {
          DEFAULT: 'rgb(var(--app-color-secondary-rgb) / <alpha-value>)',
          soft: 'rgb(var(--app-color-secondary-soft-rgb) / <alpha-value>)',
          strong: 'rgb(var(--app-color-secondary-strong-rgb) / <alpha-value>)',
        },
        warning: {
          DEFAULT: 'rgb(var(--app-color-tertiary-rgb) / <alpha-value>)',
          soft: 'rgb(var(--app-color-tertiary-soft-rgb) / <alpha-value>)',
          strong: 'rgb(var(--app-color-tertiary-strong-rgb) / <alpha-value>)',
        },
        danger: {
          DEFAULT: 'rgb(var(--app-color-danger-rgb) / <alpha-value>)',
          soft: 'rgb(var(--app-color-danger-soft-rgb) / <alpha-value>)',
          strong: 'rgb(var(--app-color-danger-strong-rgb) / <alpha-value>)',
        },
        primary: {
          DEFAULT: 'rgb(var(--app-color-primary-rgb) / <alpha-value>)',
          soft: 'rgb(var(--app-color-primary-soft-rgb) / <alpha-value>)',
          strong: 'rgb(var(--app-color-primary-strong-rgb) / <alpha-value>)',
          contrast: 'rgb(var(--ion-color-primary-contrast-rgb) / <alpha-value>)',
          50: '#f2f7fb',
          100: '#e2edf6',
          200: '#c6dced',
          300: '#9fc1de',
          400: '#709ec5',
          500: '#3c6f99',
          600: '#345f82',
          700: '#2b4f6b',
          800: '#244155',
          900: '#1f3342',
          950: '#14202b',
        },
        secondary: {
          DEFAULT: 'rgb(var(--app-color-secondary-rgb) / <alpha-value>)',
          soft: 'rgb(var(--app-color-secondary-soft-rgb) / <alpha-value>)',
          strong: 'rgb(var(--app-color-secondary-strong-rgb) / <alpha-value>)',
          contrast: 'rgb(var(--ion-color-secondary-contrast-rgb) / <alpha-value>)',
          50: '#f4f7f2',
          100: '#e8eee4',
          200: '#d2dccb',
          300: '#afc29f',
          400: '#8da379',
          500: '#6b8760',
          600: '#5b7352',
          700: '#4b5e44',
          800: '#3b4a37',
          900: '#2c382a',
          950: '#1c241b',
        },
        tertiary: {
          DEFAULT: 'rgb(var(--app-color-tertiary-rgb) / <alpha-value>)',
          soft: 'rgb(var(--app-color-tertiary-soft-rgb) / <alpha-value>)',
          strong: 'rgb(var(--app-color-tertiary-strong-rgb) / <alpha-value>)',
          contrast: 'rgb(var(--ion-color-tertiary-contrast-rgb) / <alpha-value>)',
          50: '#fbf6f1',
          100: '#f6ecdf',
          200: '#edd8bd',
          300: '#dfbb8b',
          400: '#c9995f',
          500: '#ae7b43',
          600: '#95673a',
          700: '#7a5431',
          800: '#614228',
          900: '#48321f',
          950: '#2f2014',
        },
      },
      boxShadow: {
        panel:
          '0 24px 60px -32px rgba(var(--app-shadow-color-rgb), 0.30), 0 10px 24px -18px rgba(var(--app-shadow-color-rgb), 0.22)',
      },
    },
  },
  plugins: [],
};
